In [6]:
import re
import pandas as pd
sms = pd.read_csv('spam.csv',encoding='ISO-8859-1');
sms.head()
#nltk.download('stopwords')
#nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords 

#Preprocessing the data: Remove none alphabetic characters/Make the word lower case/Remove the stop words

def mutlti_func(x):       
    WT_sms= word_tokenize(str(re.sub('[^A-Za-z]', ' ', x)).lower())
    for word in WT_sms:
        if word in stopwords.words('english'):
            WT_sms.remove(word)
    return WT_sms


sms['v2']=sms['v2'].apply(mutlti_func)
sms.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"[go, jurong, point, crazy, available, in, bugi...",NaN,NaN,NaN
1,ham,"[ok, lar, joking, wif, u, oni]",NaN,NaN,NaN
2,spam,"[free, entry, a, wkly, comp, win, fa, cup, fin...",NaN,NaN,NaN
3,ham,"[u, dun, say, early, hor, u, c, already, say]",NaN,NaN,NaN
4,ham,"[nah, don, think, goes, usf, lives, around, th...",NaN,NaN,NaN

In [7]:
from nltk.stem.porter import PorterStemmer
from spellchecker import SpellChecker


# Stemming / Spelling 
spell = SpellChecker()
stemmer = PorterStemmer()

def stem_spell_fuc(x):
    for i in range(len(x)):
        #x[i] = stemmer.stem(spell.correction(x[i]))
        x[i] = stemmer.stem(x[i])
    return x

sms['v2']=sms['v2'].apply(stem_spell_fuc)
sms.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"[go, jurong, point, crazi, avail, in, bugi, n,...",NaN,NaN,NaN
1,ham,"[ok, lar, joke, wif, u, oni]",NaN,NaN,NaN
2,spam,"[free, entri, a, wkli, comp, win, fa, cup, fin...",NaN,NaN,NaN
3,ham,"[u, dun, say, earli, hor, u, c, alreadi, say]",NaN,NaN,NaN
4,ham,"[nah, don, think, goe, usf, live, around, though]",NaN,NaN,NaN

In [16]:
def join_fuc(x):
    x = " ".join(x)
    return x

sms.columns=["v1","v2","v3","v4","v5"]
sms['v3']=sms['v2'].apply(join_fuc)
sms.head()

,v1,v2,v3,v4,v5
0,ham,"[go, jurong, point, crazi, avail, in, bugi, n,...",go jurong point crazi avail in bugi n great wo...,NaN,NaN
1,ham,"[ok, lar, joke, wif, u, oni]",ok lar joke wif u oni,NaN,NaN
2,spam,"[free, entri, a, wkli, comp, win, fa, cup, fin...",free entri a wkli comp win fa cup final tkt st...,NaN,NaN
3,ham,"[u, dun, say, earli, hor, u, c, alreadi, say]",u dun say earli hor u c alreadi say,NaN,NaN
4,ham,"[nah, don, think, goe, usf, live, around, though]",nah don think goe usf live around though,NaN,NaN

In [45]:
def joincomm(x):
    temp2=re.sub(" ",",",x)
    return temp2
sms['v4']=sms['v3'].apply(joincomm)
sms.head()

,v1,v2,v3,v4,v5
0,ham,"[go, jurong, point, crazi, avail, in, bugi, n,...",go jurong point crazi avail in bugi n great wo...,"go,jurong,point,crazi,avail,in,bugi,n,great,wo...",NaN
1,ham,"[ok, lar, joke, wif, u, oni]",ok lar joke wif u oni,"ok,lar,joke,wif,u,oni",NaN
2,spam,"[free, entri, a, wkli, comp, win, fa, cup, fin...",free entri a wkli comp win fa cup final tkt st...,"free,entri,a,wkli,comp,win,fa,cup,final,tkt,st...",NaN
3,ham,"[u, dun, say, earli, hor, u, c, alreadi, say]",u dun say earli hor u c alreadi say,"u,dun,say,earli,hor,u,c,alreadi,say",NaN
4,ham,"[nah, don, think, goe, usf, live, around, though]",nah don think goe usf live around though,"nah,don,think,goe,usf,live,around,though",NaN

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(token_pattern=u'(?u)\\b\\w+\\b')

result=vect.fit_transform(sms['v3']).toarray()

result

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
 corpus = [
'This is the first document.',
'This is the second second document.',
'And the third one.',
'Is this the first document?',
]
X = vect.fit_transform(corpus).toarray()
X

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [64]:
sms['v3']

0       go jurong point crazi avail in bugi n great wo...
1                                   ok lar joke wif u oni
2       free entri a wkli comp win fa cup final tkt st...
3                     u dun say earli hor u c alreadi say
4                nah don think goe usf live around though
5       freemsg hey darl week s now no word back d lik...
6       even brother not like speak treat me like aid ...
7       per request mell mell oru minnaminungint nurun...
8       winner a valu network custom have select recei...
9       your mobil month more u r entitl updat latest ...
10      m gon na home soon t want talk thi stuff anymo...
11      six chanc win cash pound txt csh send to cost ...
12      urgent have week free membership our prize jac...
13      ve search the right word thank breather promi ...
14                                  have date sunday will
15      xxxmobilemovieclub use credit click wap link t...
16                                           oh k m watch
17      eh u rememb spell name ye did v naughti make i...
18                  fine way u feel that s the way gota b
19      england v macedonia dont miss goal team news t...
20                             that seriou you spell name
21                              m go tri month ha ha joke
22                      pay first lar when da stock comin
23      aft finish lunch i go str lor ard smth lor u f...
24            ffffffffff alright way can meet with sooner
25      forc to eat slice m realli hungri tho suck mar...
26                                      lol alway convinc
27      you catch bu you fri egg you make tea you eat ...
28           m back amp re pack car i let know there room
29            ahhh work vagu rememb what it feel like lol
                              ...
5542                        armand say get ass to epsilon
5543                  u still havent got urself jacket ah
5544    take derek amp taylor walmart i m not back tim...
5545                    hi in durban you still thi number
5546                           ic are lotta childporn car
5547    your contract mobil mnth latest motorola nokia...
5548                                  i tri all weekend v
5549    know wot peopl wear shirt jumper hat belt all ...
5550                              cool time think can get
5551                     wen you get spiritu deep s great
5552    a safe trip nigeria wish happi veri soon compa...
5553                                hahaha use brain dear
5554    well keep mind ve got enough ga one round trip...
5555    yeh indian nice tho did kane off bit he shud g...
5556           ye have that whi u text pshew miss so much
5557    i meant calcul that lt gt unit lt gt school re...
5558                                  sorri ll call later
5559              you t in next lt gt hour imma flip shit
5560                              anyth lor juz of us lor
5561        get out thi dump heap mom decid come low bore
5562    ok lor soni ericsson salesman ask shuhui she s...
5563                                     ard like dat lor
5564         don you wait til least wednesday see you get
5565                                              huh lei
5566    remind o get pound free call credit detail gre...
5567    nd time tri contact u u have won pound prize c...
5568                                b go esplanad fr home
5569                        piti in mood that ani suggest
5570    guy some bitch act like i d interest buy somet...
5571                                    rofl true it name
Name: v3, Length: 5572, dtype: object